{{-- resources/views/facilities.blade.php --}}
@extends('layouts.app')

@section('title', 'Fasilitas Laboratorium - Laboratorium Fisika Dasar')

@section('content')
<!-- Hero Section -->
<section class="relative min-h-[70vh] flex items-center justify-center overflow-hidden">
    <!-- Background Image with Blue Overlay -->
    <div class="absolute inset-0 z-0">
        <img src="{{ asset('images/hero.jpg') }}"
             alt="Fasilitas Laboratorium"
             class="w-full h-full object-cover">
        <div class="absolute inset-0 bg-gradient-to-br from-blue-700/90 via-blue-800/80 to-blue-900/70"></div>
    </div>

    <!-- Animated Particles - Molecular Animation -->
    <div class="absolute inset-0 z-10">
        <div class="molecules-container" id="molecules-container">
            {{-- Molecules will be generated by JavaScript --}}
        </div>
    </div>

    <!-- Content -->
    <div class="relative z-20 mx-6 px-4 sm:px-6 lg:px-8 text-center max-w-5xl">
        <!-- Breadcrumb -->
        <div class="scroll-animate mb-8 opacity-0" data-animation="fade-down">
            <nav class="flex justify-center" aria-label="Breadcrumb">
                <ol class="inline-flex items-center space-x-1 md:space-x-3 bg-white/10 backdrop-blur-sm rounded-full px-6 py-3">
                    <li class="inline-flex items-center">
                        <a href="{{ route('home') }}" class="text-blue-200 hover:text-white transition-colors duration-200 flex items-center">
                            <i class="fas fa-home mr-2"></i>Beranda
                        </a>
                    </li>
                    <li>
                        <div class="flex items-center">
                            <i class="fas fa-chevron-right text-blue-300 mx-3"></i>
                            <span class="text-white font-medium">Fasilitas Laboratorium</span>
                        </div>
                    </li>
                </ol>
            </nav>
        </div>

        <!-- Main Title -->
        <div class="scroll-animate mb-8 opacity-0" data-animation="fade-up" data-delay="200">
            <h1 class="font-poppins text-5xl md:text-7xl font-bold leading-tight mb-6">
                <span class="text-white">Fasilitas</span>
                <span class="bg-gradient-to-r from-yellow-400 to-orange-400 bg-clip-text text-transparent drop-shadow-lg"> Terdepan</span>
            </h1>
            <p class="text-xl md:text-2xl text-blue-100 max-w-4xl mx-auto leading-relaxed">
                Jelajahi ruang-ruang dengan fasilitas lengkap dan teknologi modern untuk mendukung pembelajaran fisika yang optimal
            </p>
        </div>
    </div>
</section>

<!-- Main Facilities Section -->
<section class="py-24 bg-gradient-to-b from-gray-50 to-white">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <!-- Section Header -->
        <div class="text-center mb-20 scroll-animate" data-animation="fade-down">
            <div class="inline-flex items-center px-6 py-3 bg-blue-50 border border-blue-200 rounded-full text-blue-700 text-sm font-semibold mb-6 shadow-sm">
                <i class="fas fa-building mr-2"></i>
                Fasilitas Unggulan
            </div>
            <h2 class="font-poppins text-4xl md:text-6xl font-bold text-gray-900 mb-6">
                Ruang <span class="bg-gradient-to-r from-blue-600 to-blue-800 bg-clip-text text-transparent">Berkualitas</span>
            </h2>
            <p class="text-gray-600 text-lg md:text-xl max-w-4xl mx-auto leading-relaxed">
                Setiap ruang dirancang khusus dengan standar internasional dan teknologi terdepan untuk mendukung kegiatan pembelajaran dan penelitian yang optimal.
            </p>
        </div>

        <!-- Facilities Grid Layout -->
        <div class="space-y-24">
            @foreach($facilities as $index => $facility)
            <!-- Facility {{ $index + 1 }} -->
            <div class="relative">
                <!-- Background Decoration -->
                <div class="absolute inset-0 -z-10">
                    <div class="absolute {{ $index % 2 == 0 ? 'right-0' : 'left-0' }} top-1/2 transform -translate-y-1/2 w-96 h-96 bg-blue-{{ $facility['color_intensity'] }}/5 rounded-full blur-3xl"></div>
                </div>

                <div class="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 items-center">
                    @if($index % 2 == 0)
                        <!-- Content Left (7 columns) -->
                        <div class="lg:col-span-7 space-y-8 scroll-animate" data-animation="slide-left" data-delay="{{ $index * 200 }}">
                            <!-- Header -->
                            <div class="space-y-6">
                                <div class="inline-flex items-center px-4 py-2 bg-blue-{{ $facility['color_intensity'] }}/10 border border-blue-{{ $facility['color_intensity'] }}/20 rounded-full text-blue-{{ $facility['color_intensity'] }} text-sm font-semibold">
                                    <i class="{{ $facility['icon'] }} mr-2"></i>
                                    {{ $facility['name'] }}
                                </div>
                                <h3 class="text-3xl lg:text-4xl font-bold text-gray-900 leading-tight">
                                    {{ $facility['title'] }}
                                </h3>
                                <p class="text-gray-700 text-lg leading-relaxed">
                                    {{ $facility['description'] }}
                                </p>
                            </div>

                            <!-- Features -->
                            <div class="space-y-6">
                                <h4 class="text-xl font-bold text-gray-900">Fasilitas Unggulan</h4>
                                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                    @foreach($facility['features'] as $feature)
                                    <div class="flex items-start space-x-3 group">
                                        <div class="w-6 h-6 bg-blue-{{ $facility['color_intensity'] }} rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 group-hover:scale-110 transition-transform duration-300">
                                            <i class="fas fa-check text-white text-xs"></i>
                                        </div>
                                        <span class="text-gray-700 group-hover:text-blue-{{ $facility['color_intensity'] }} transition-colors duration-300">{{ $feature }}</span>
                                    </div>
                                    @endforeach
                                </div>
                            </div>

                            <!-- Capacity Info -->
                            <div class="flex items-center space-x-6 pt-4 border-t border-gray-200">
                                <div class="flex items-center text-gray-600">
                                    <i class="fas fa-users text-blue-{{ $facility['color_intensity'] }} mr-2"></i>
                                    <span class="font-medium">{{ $facility['capacity'] }}</span>
                                </div>
                            </div>
                        </div>

                        <!-- Image Right (5 columns) -->
                        <div class="lg:col-span-5 scroll-animate" data-animation="slide-right" data-delay="{{ ($index * 200) + 100 }}">
                            <div class="relative overflow-hidden rounded-2xl shadow-2xl group">
                                <img src="{{ asset('images/facilities/' . $facility['image']) }}"
                                     alt="{{ $facility['title'] }}"
                                     class="w-full h-64 lg:h-80 object-cover transform group-hover:scale-105 transition-transform duration-700">
                                <div class="absolute inset-0 bg-gradient-to-t from-blue-900/40 via-transparent to-transparent"></div>

                                <!-- Floating Icon -->
                                <div class="absolute top-6 right-6">
                                    <div class="w-12 h-12 bg-white/90 backdrop-blur-sm rounded-xl flex items-center justify-center shadow-lg transform rotate-3 hover:rotate-0 transition-transform duration-300">
                                        <i class="{{ $facility['icon'] }} text-blue-{{ $facility['color_intensity'] }} text-lg"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @else
                        <!-- Image Left (5 columns) -->
                        <div class="lg:col-span-5 scroll-animate" data-animation="slide-left" data-delay="{{ $index * 200 }}">
                            <div class="relative overflow-hidden rounded-2xl shadow-2xl group">
                                <img src="{{ asset('images/facilities/' . $facility['image']) }}"
                                     alt="{{ $facility['title'] }}"
                                     class="w-full h-64 lg:h-80 object-cover transform group-hover:scale-105 transition-transform duration-700">
                                <div class="absolute inset-0 bg-gradient-to-t from-blue-900/40 via-transparent to-transparent"></div>

                                <!-- Floating Icon -->
                                <div class="absolute top-6 left-6">
                                    <div class="w-12 h-12 bg-white/90 backdrop-blur-sm rounded-xl flex items-center justify-center shadow-lg transform -rotate-3 hover:rotate-0 transition-transform duration-300">
                                        <i class="{{ $facility['icon'] }} text-blue-{{ $facility['color_intensity'] }} text-lg"></i>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Content Right (7 columns) -->
                        <div class="lg:col-span-7 space-y-8 scroll-animate" data-animation="slide-right" data-delay="{{ ($index * 200) + 100 }}">
                            <!-- Header -->
                            <div class="space-y-6">
                                <div class="inline-flex items-center px-4 py-2 bg-blue-{{ $facility['color_intensity'] }}/10 border border-blue-{{ $facility['color_intensity'] }}/20 rounded-full text-blue-{{ $facility['color_intensity'] }} text-sm font-semibold">
                                    <i class="{{ $facility['icon'] }} mr-2"></i>
                                    {{ $facility['name'] }}
                                </div>
                                <h3 class="text-3xl lg:text-4xl font-bold text-gray-900 leading-tight">
                                    {{ $facility['title'] }}
                                </h3>
                                <p class="text-gray-700 text-lg leading-relaxed">
                                    {{ $facility['description'] }}
                                </p>
                            </div>
                            

                            <!-- Features -->
                            <div class="space-y-6">
                                <h4 class="text-xl font-bold text-gray-900">Fasilitas Unggulan</h4>
                                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                    @foreach($facility['features'] as $feature)
                                    <div class="flex items-start space-x-3 group">
                                        <div class="w-6 h-6 bg-blue-{{ $facility['color_intensity'] }} rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 group-hover:scale-110 transition-transform duration-300">
                                            <i class="fas fa-check text-white text-xs"></i>
                                        </div>
                                        <span class="text-gray-700 group-hover:text-blue-{{ $facility['color_intensity'] }} transition-colors duration-300">{{ $feature }}</span>
                                    </div>
                                    @endforeach
                                </div>
                            </div>

                            <!-- Capacity Info -->
                            <div class="flex items-center space-x-6 pt-4 border-t border-gray-200">
                                <div class="flex items-center text-gray-600">
                                    <i class="fas fa-users text-blue-{{ $facility['color_intensity'] }} mr-2"></i>
                                    <span class="font-medium">{{ $facility['capacity'] }}</span>
                                </div>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
            @endforeach
        </div>
    </div>
</section>

<!-- CTA Section -->
<section class="py-20 bg-gradient-to-r from-blue-600 to-blue-800 relative overflow-hidden">
    <!-- Background Pattern -->
    <div class="absolute inset-0 opacity-10">
        <div class="absolute inset-0" style="background-image: url('data:image/svg+xml,<svg width="60" height="60" viewBox="0 0 60 60" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><g fill="%23ffffff" fill-opacity="0.3"><circle cx="30" cy="30" r="2"/></g></svg>')"></div>
    </div>

    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 relative">
        <div class="text-center scroll-animate" data-animation="fade-up">
            <h3 class="text-4xl md:text-5xl font-bold text-white mb-6">
                Butuh Informasi Lebih Lanjut?
            </h3>
            <p class="text-blue-100 text-lg md:text-xl mb-10 max-w-3xl mx-auto leading-relaxed">
                Hubungi tim kami untuk konsultasi mengenai penggunaan fasilitas laboratorium atau untuk mengatur kunjungan dan demo peralatan.
            </p>
            <div class="flex flex-col sm:flex-row gap-6 justify-center items-center">
                <a href="#" class="bg-white text-blue-600 px-8 py-4 rounded-2xl font-semibold hover:bg-gray-50 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1 flex items-center">
                    <i class="fas fa-phone mr-3"></i>Hubungi Kami
                </a>
                <a href="#" class="border-2 border-white text-white px-8 py-4 rounded-2xl font-semibold hover:bg-white hover:text-blue-600 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1 flex items-center">
                    <i class="fas fa-calendar mr-3"></i>Jadwalkan Kunjungan
                </a>
            </div>
        </div>
    </div>
</section>

<style>
/* Enhanced Gradient Text */
.bg-clip-text {
    -webkit-background-clip: text;
    background-clip: text;
    -webkit-text-fill-color: transparent;
}

/* ===== MOLECULAR ANIMATION CSS ===== */
.molecules-container {
    position: absolute;
    width: 100%;
    height: 100%;
    overflow: hidden;
}

.molecule {
    position: absolute;
    width: 60px;
    height: 60px;
    opacity: 0.8;
    pointer-events: none;
}

.atom {
    position: absolute;
    border-radius: 50%;
    background: radial-gradient(circle, rgba(255,255,255,0.9), rgba(100,200,255,0.4));
    box-shadow: 0 0 20px rgba(255,255,255,0.6);
}

.atom.core {
    width: 12px;
    height: 12px;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    background: radial-gradient(circle, #ffd700, #ff6b35);
    box-shadow: 0 0 25px rgba(255, 215, 0, 0.8);
    animation: pulse 2s infinite ease-in-out;
}

.atom.electron {
    width: 6px;
    height: 6px;
    background: radial-gradient(circle, #00d4ff, #0066cc);
    box-shadow: 0 0 15px rgba(0, 212, 255, 0.7);
}

.orbit {
    position: absolute;
    border: 1px solid rgba(255,255,255,0.3);
    border-radius: 50%;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}

.orbit-1 {
    width: 40px;
    height: 40px;
    animation: rotate 4s linear infinite;
}

.orbit-2 {
    width: 55px;
    height: 55px;
    animation: rotate 6s linear infinite reverse;
}

.orbit-1 .electron {
    top: -3px;
    left: 50%;
    transform: translateX(-50%);
}

.orbit-2 .electron {
    top: -3px;
    left: 50%;
    transform: translateX(-50%);
}

@keyframes rotate {
    from { transform: translate(-50%, -50%) rotate(0deg); }
    to { transform: translate(-50%, -50%) rotate(360deg); }
}

@keyframes pulse {
    0%, 100% {
        transform: translate(-50%, -50%) scale(1);
        box-shadow: 0 0 25px rgba(255, 215, 0, 0.8);
    }
    50% {
        transform: translate(-50%, -50%) scale(1.3);
        box-shadow: 0 0 35px rgba(255, 215, 0, 1);
    }
}

.molecule.float {
    animation: moleculeFloat 18s infinite linear;
}

@keyframes moleculeFloat {
    0% {
        transform: translateY(100vh) translateX(-50px) rotate(0deg) scale(0.5);
        opacity: 0;
    }
    5% {
        opacity: 0.8;
        transform: translateY(95vh) translateX(-40px) rotate(18deg) scale(0.7);
    }
    25% {
        transform: translateY(75vh) translateX(-10px) rotate(90deg) scale(1);
    }
    50% {
        transform: translateY(50vh) translateX(20px) rotate(180deg) scale(1.1);
    }
    75% {
        transform: translateY(25vh) translateX(40px) rotate(270deg) scale(1);
    }
    95% {
        opacity: 0.8;
        transform: translateY(5vh) translateX(60px) rotate(342deg) scale(0.7);
    }
    100% {
        transform: translateY(-10vh) translateX(80px) rotate(360deg) scale(0.5);
        opacity: 0;
    }
}

/* Enhanced molecular variants */
.molecule.large {
    transform: scale(1.3);
}

.molecule.small {
    transform: scale(0.7);
}

.molecule.gold .atom.core {
    background: radial-gradient(circle, #ffd700, #ffb347);
    box-shadow: 0 0 25px rgba(255, 215, 0, 0.9);
}

.molecule.blue .atom.core {
    background: radial-gradient(circle, #00d4ff, #0088cc);
    box-shadow: 0 0 25px rgba(0, 212, 255, 0.8);
}

.molecule.green .atom.core {
    background: radial-gradient(circle, #26de81, #20bf6b);
    box-shadow: 0 0 25px rgba(38, 222, 129, 0.8);
}

/* Scroll Animations */
.scroll-animate {
    opacity: 0;
    transition: all 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94);
}

.scroll-animate[data-animation="fade-down"] {
    transform: translateY(-60px);
}

.scroll-animate[data-animation="fade-up"] {
    transform: translateY(60px);
}

.scroll-animate[data-animation="slide-left"] {
    transform: translateX(-100px);
}

.scroll-animate[data-animation="slide-right"] {
    transform: translateX(100px);
}

.scroll-animate.animate {
    opacity: 1;
    transform: translateY(0) translateX(0);
}

/* Enhanced Hover Effects */
.group:hover .group-hover\:scale-110 {
    transform: scale(1.1);
}

.group:hover .group-hover\:translate-x-1 {
    transform: translateX(0.25rem);
}

/* Modern Card Shadows */
.shadow-card {
    box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
}

.shadow-card-hover {
    box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
}

/* Responsive Adjustments */
@media (max-width: 768px) {
    .scroll-animate[data-animation="fade-down"],
    .scroll-animate[data-animation="fade-up"] {
        transform: translateY(40px);
    }

    .scroll-animate[data-animation="slide-left"],
    .scroll-animate[data-animation="slide-right"] {
        transform: translateX(0) translateY(40px);
    }

    .molecule {
        width: 40px;
        height: 40px;
    }

    .orbit-1 {
        width: 30px;
        height: 30px;
    }

    .orbit-2 {
        width: 40px;
        height: 40px;
    }
}

/* Loading Animation */
@keyframes shimmer {
    0% {
        background-position: -1000px 0;
    }
    100% {
        background-position: 1000px 0;
    }
}

.shimmer {
    background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
    background-size: 1000px 100%;
    animation: shimmer 2s infinite;
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // ===== MOLECULAR ANIMATION JAVASCRIPT =====
    function createMolecularAnimation() {
        const container = document.getElementById('molecules-container');
        if (!container) return;

        const moleculeTypes = ['gold', 'blue', 'green'];
        const moleculeSizes = ['small', 'normal', 'large'];

        function createMolecule() {
            const molecule = document.createElement('div');
            const type = moleculeTypes[Math.floor(Math.random() * moleculeTypes.length)];
            const size = moleculeSizes[Math.floor(Math.random() * moleculeSizes.length)];

            molecule.className = `molecule float ${type} ${size}`;
            molecule.style.left = Math.random() * 100 + '%';
            molecule.style.animationDelay = Math.random() * 5 + 's';
            molecule.style.animationDuration = (15 + Math.random() * 10) + 's';

            // Core atom (nucleus)
            const core = document.createElement('div');
            core.className = 'atom core';
            molecule.appendChild(core);

            // Create orbits and electrons
            const numOrbits = Math.random() > 0.5 ? 2 : 1;
            for (let i = 1; i <= numOrbits; i++) {
                const orbit = document.createElement('div');
                orbit.className = `orbit orbit-${i}`;

                // Add electron to orbit
                const electron = document.createElement('div');
                electron.className = 'atom electron';
                orbit.appendChild(electron);

                molecule.appendChild(orbit);
            }

            container.appendChild(molecule);

            // Remove molecule after animation completes
            setTimeout(() => {
                if (container.contains(molecule)) {
                    container.removeChild(molecule);
                }
            }, 20000);
        }

        // Create initial molecules
        for (let i = 0; i < 3; i++) {
            setTimeout(() => createMolecule(), i * 2000);
        }

        // Continue creating molecules
        const moleculeInterval = setInterval(createMolecule, 3000);

        // Cleanup function for when page is unloaded
        window.addEventListener('beforeunload', () => {
            clearInterval(moleculeInterval);
        });
    }

    // Initialize molecular animation
    createMolecularAnimation();

    // Intersection Observer for scroll animations
    const animatedElements = document.querySelectorAll('.scroll-animate');

    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                const delay = entry.target.dataset.delay || 0;
                setTimeout(() => {
                    entry.target.classList.add('animate');
                }, delay);
            }
        });
    }, {
        threshold: 0.1,
        rootMargin: '0px 0px -50px 0px'
    });

    animatedElements.forEach(element => {
        observer.observe(element);
    });

    // Parallax effect for hero section
    window.addEventListener('scroll', () => {
        const scrolled = window.pageYOffset;
        const parallax = document.querySelector('.molecules-container');
        if (parallax) {
            const speed = scrolled * 0.3;
            parallax.style.transform = `translateY(${speed}px)`;
        }
    });

    // Smooth scrolling for anchor links
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
            }
        });
    });

    // Performance optimization: pause animations when not in view
    const heroSection = document.querySelector('section');
    const heroObserver = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            const molecules = entry.target.querySelectorAll('.molecule');
            if (entry.isIntersecting) {
                molecules.forEach(molecule => {
                    molecule.style.animationPlayState = 'running';
                });
            } else {
                molecules.forEach(molecule => {
                    molecule.style.animationPlayState = 'paused';
                });
            }
        });
    });

    if (heroSection) {
        heroObserver.observe(heroSection);
    }
});
</script>
@endsection
